---
# tasks file for vdbench
- include_vars: "{{ vars_file }}"
- assert:
   that:
    - vconf != ""
    - vdarcht != ""
    - vdpath != ""
    - vdbshell != ""
- name: Create THE Folder
  file: path="{{vdpath}}{{ansible_machine_id}}" state=directory mode=0777
- name: Mount share (NFS)
  mount: name="{{vdpath}}{{ansible_machine_id}}" src="{{vip1}}:{{volume}}{{ansible_machine_id}}" fstype=nfs opts="rw,sync" state=mounted
- name: Copy config
  template: src={{vconftmp}} dest="{{vdpath}}{{ansible_machine_id}}{{vconf}}"
- name: Unzip vdb to folder
  unarchive: src={{vdarcht}} dest="{{vdpath}}{{ansible_machine_id}}"
- name: Run IO
  shell: "{{vdpath}}{{ansible_machine_id}}{{vdbshell}} -f {{vdpath}}{{ansible_machine_id}}{{vconf}}"
  async: 40
  poll: 0

