---
# tasks file for vdbench
- assert:
   that:
    - vconf != ""
    - vdarch != ""
    - vdpath != ""
    - vdb != ""
- name: Configure resolvconf
  lineinfile: dest=/etc/resolv.conf line='nameserver 8.8.8.8'
- include: apt.yml
  when: ansible_pkg_mgr == 'apt'
- include: yum.yml
  when: ansible_pkg_mgr == 'yum'
- name: Create THE Folder
  file: path={{ vdpath }} state=directory mode=0777
- name: Copy config
  template: src=../../common/templates/{{ vconf }}.j2 dest={{ vdpath }}{{ vconf }}
- name: Unzip vdb to folder
  unarchive: src={{vdarch}} dest={{ vdpath }}
- name: Run IO
  shell: "{{ vdpath }}{{ vdb }} -f {{ vdpath }}{{ vconf }}"
  async: 40 
  poll: 0
