---
- include_vars: "{{ vars_file }}"
- assert:
   that:
    - vconf != ""
    - vdarcht != ""
    - vdpath != ""
    - vdbshell != ""
- name: Configure resolvconf
  lineinfile: dest=/etc/resolv.conf line='nameserver 8.8.8.8'
- include: apt.yml
  when: ansible_pkg_mgr == 'apt'
- include: yum.yml
  when: ansible_pkg_mgr == 'yum'
- name: Create THE Folder
  file: path="{{vdpath}}" state=directory mode=0777
- name: Create THE Folder fsload
  file: path="{{vdpath}}/fsload" state=directory mode=0777
- name: Mount share (NFS)
  mount: name="{{vdpath}}/fsload" src="{{vip2}}:{{nfs2}}{{inventory_hostname}}" fstype=nfs opts="rw,sync" state=mounted
- name: Copy config
  template: src={{vconftmp}} dest="{{vdpath}}{{vconf}}"
- name: Unzip vdb to folder
  unarchive: src={{vdarcht}} dest="{{vdpath}}"
- name: Run IO
  shell: "{{vdpath}}{{vdbshell}} -f {{vdpath}}{{vconf}}"
  async: 40000
  poll: 0
